### ISSUE TITLE
E: Unable to locate package tkinter

### ISSUE THREAD

**Issue by tratatun** [garyexplains/examples#9]
I'm not really familiar with linux, and stuck in getting this error when trying to install stuff from point **Get the compilers etc** in **examples/Raspberry Pi Pico/C/** readme instructions. 

I have fresh installed WSL Ubuntu 20.04 LTS and also tried on WSL Ubuntu 18.04 LTS 
#
me@my:~$ sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libssl-dev tk tkinter python3-tk

Output:
>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>E: Unable to locate package tkinter

**Comment by effegit** [comment]
use this command:  "sudo apt install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libssl-dev tk python3-tk "

**Comment by bro-kengrl0810** [comment]
python3-dev I'm having the same issue.  I can't get it to stop..
